TOP = "_tp/"
MIDDLE = "_md/"
BOTTOM = "_bt/"
LEFT = "_lt/"
CENTER = "_ct/"
RIGHT = "_rg/"


TOPCENTER = (CENTER, TOP)
TOPLEFT = (LEFT, TOP)
TOPRIGHT = (RIGHT, TOP)
MIDDLECENTER = (CENTER, MIDDLE)
MIDDLELEFT = (LEFT, MIDDLE)
MIDDLERIGHT = (RIGHT, MIDDLE)
BOTTOMCENTER = (CENTER, BOTTOM)
BOTTOMLEFT = (LEFT, BOTTOM)
BOTTOMRIGHT = (RIGHT, BOTTOM)
