# Generated by Django 2.2.27 on 2023-04-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_ontochain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
    ]
