# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class FormatType(str, enum.Enum):
    """
    An enumeration.
    """

    TABULAR = "Tabular"
    FREE_TEXT = "FreeText"

    def visit(self, tabular: typing.Callable[[], T_Result], free_text: typing.Callable[[], T_Result]) -> T_Result:
        if self is FormatType.TABULAR:
            return tabular()
        if self is FormatType.FREE_TEXT:
            return free_text()
