# This file was auto-generated by Fern from our API Definition.

import typing

from .amazon_security_lake_integration import AmazonSecurityLakeIntegration
from .azure_boards_integration import AzureBoardsIntegration
from .data_dog_integration import DataDogIntegration
from .data_hub_integration import DataHubIntegration
from .email_integration_input import EmailIntegrationInput
from .jira_integration import JiraIntegration
from .monday_integration import MondayIntegration
from .pager_duty_integration import PagerDutyIntegration
from .seemplicity_integration import SeemplicityIntegration
from .slack_integration_input import SlackIntegrationInput
from .teams_integration import TeamsIntegration
from .web_hook_integration_input import WebHookIntegrationInput

IntegrationInputProperties = typing.Union[
    SlackIntegrationInput,
    EmailIntegrationInput,
    WebHookIntegrationInput,
    MondayIntegration,
    DataDogIntegration,
    TeamsIntegration,
    JiraIntegration,
    DataHubIntegration,
    PagerDutyIntegration,
    SeemplicityIntegration,
    AmazonSecurityLakeIntegration,
    AzureBoardsIntegration,
]
