CACHE_SIZE = 256

NAMED_REGEX = r':[\w|\d]*'

MYSQL, POSTGRESQL, ORACLE, SQL_SERVER, SQLITE, UNKNOW = 'MySQL', 'PostgreSQL', 'Oracle', 'SQL Server', 'SQLite', 'Unknow'

MYSQLCLIENT, PYMYSQL, MYSQL_CONNECTOR, PSYCOPG2, PG8000, PY_POSTGRESQL, PYGRESQL, ORACLEDB, SQLITE3 = 'MySQLdb', 'pymysql', 'mysql.connector', \
    'psycopg2', 'pg8000', 'postgresql.driver.dbapi20', 'pgdb', 'oracledb', 'sqlite3'

DRIVERS = {MYSQLCLIENT: MYSQL, PYMYSQL: MYSQL, MYSQL_CONNECTOR: MYSQL, PSYCOPG2: POSTGRESQL, PG8000: POSTGRESQL, PY_POSTGRESQL: POSTGRESQL, \
           PYGRESQL: POSTGRESQL, ORACLEDB: ORACLE, SQLITE3: SQLITE}

PARAM_DRIVER, PARAM_SHOW_SQL, PARAM_TRANS_PLACEHOLDER, PARAM_DEBUG, PARAM_POOL_SIZE = 'driver', 'show_sql', 'trans_placeholder', 'debug', 'pool_size'
