# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ConfigTemplatesInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, values=None):  # noqa: E501
        """ConfigTemplatesInner - a model defined in OpenAPI

        :param name: The name of this ConfigTemplatesInner.  # noqa: E501
        :type name: str
        :param values: The values of this ConfigTemplatesInner.  # noqa: E501
        :type values: Dict[str, str]
        """
        self.openapi_types = {
            'name': str,
            'values': Dict[str, str]
        }

        self.attribute_map = {
            'name': 'name',
            'values': 'values'
        }

        self._name = name
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigTemplatesInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Config_templates_inner of this ConfigTemplatesInner.  # noqa: E501
        :rtype: ConfigTemplatesInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ConfigTemplatesInner.

        the config file path name  # noqa: E501

        :return: The name of this ConfigTemplatesInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigTemplatesInner.

        the config file path name  # noqa: E501

        :param name: The name of this ConfigTemplatesInner.
        :type name: str
        """

        self._name = name

    @property
    def values(self):
        """Gets the values of this ConfigTemplatesInner.

        The config values for the template file  # noqa: E501

        :return: The values of this ConfigTemplatesInner.
        :rtype: Dict[str, str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this ConfigTemplatesInner.

        The config values for the template file  # noqa: E501

        :param values: The values of this ConfigTemplatesInner.
        :type values: Dict[str, str]
        """

        self._values = values
