
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-30T13:02:47+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "a614666934c737173e0d4432c99c3090b8ebcd14",
 "version": "0.5.0b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
