VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('01')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('12')
MAJOR_VERSION = 1
MINOR_VERSION = 14
PATCH_VERSION = 202308011012
version_date = '2023/08/01 10:12'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
