# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drift_protocol/common/status_code.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drift_protocol/common/status_code.proto',
  package='drift.proto.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'drift_protocol/common/status_code.proto\x12\x12\x64rift.proto.common*\xa9\x02\n\nStatusCode\x12\x08\n\x04GOOD\x10\x00\x12\x0e\n\tUNCERTAIN\x10\x80\x02\x12\x1b\n\x16UNCERTAIN_SERVICE_BUSY\x10\x81\x02\x12\x08\n\x03\x42\x41\x44\x10\x80\x04\x12\x1a\n\x15\x42\x41\x44_MALFORMED_REQUEST\x10\x81\x04\x12\x1b\n\x16\x42\x41\x44_MALFORMED_RESPONSE\x10\x82\x04\x12\x19\n\x14\x42\x41\x44_INVALID_ARGUMENT\x10\x83\x04\x12\x17\n\x12\x42\x41\x44_INTERNAL_ERROR\x10\x84\x04\x12\x1c\n\x17\x42\x41\x44_COMMUNICATION_ERROR\x10\x85\x04\x12\x15\n\x10\x42\x41\x44_SOURCE_STATE\x10\x86\x04\x12\x1c\n\x17\x42\x41\x44_SOURCE_DATA_QUALITY\x10\x87\x04\x12\x1a\n\x15\x42\x41\x44_DATA_READ_TIMEOUT\x10\x88\x04\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='drift.proto.common.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOOD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNCERTAIN', index=1, number=256,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNCERTAIN_SERVICE_BUSY', index=2, number=257,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD', index=3, number=512,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_MALFORMED_REQUEST', index=4, number=513,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_MALFORMED_RESPONSE', index=5, number=514,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_INVALID_ARGUMENT', index=6, number=515,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_INTERNAL_ERROR', index=7, number=516,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_COMMUNICATION_ERROR', index=8, number=517,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_SOURCE_STATE', index=9, number=518,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_SOURCE_DATA_QUALITY', index=10, number=519,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD_DATA_READ_TIMEOUT', index=11, number=520,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=64,
  serialized_end=361,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
GOOD = 0
UNCERTAIN = 256
UNCERTAIN_SERVICE_BUSY = 257
BAD = 512
BAD_MALFORMED_REQUEST = 513
BAD_MALFORMED_RESPONSE = 514
BAD_INVALID_ARGUMENT = 515
BAD_INTERNAL_ERROR = 516
BAD_COMMUNICATION_ERROR = 517
BAD_SOURCE_STATE = 518
BAD_SOURCE_DATA_QUALITY = 519
BAD_DATA_READ_TIMEOUT = 520


DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
