
dict={
'Afghanistan' : 'AFN',
'Albania' : 'ALL',
'Algeria' : 'DZD',
'American Samoa' : 'USD',
'Andorra' : 'EUR',
'Angola' : 'AOA',
'Anguilla' : 'XCD',
'Antigua and Barbuda' : 'XCD',
'Argentina' : 'ARS',
'Armenia' : 'AMD',
'Aruba' : 'AWG',
'Australia' : 'AUD',
'Austria' : 'EUR',
'Azerbaijan' : 'AZN',
'Bahamas' : 'BSD',
'Bahrain' : 'BHD',
'Bangladesh' : 'BDT',
'Barbados' : 'BBD',
'Belarus' : 'BYN',
'Belgium' : 'EUR',
'Belize' : 'BZD',
'Benin' : 'XOF',
'Bermuda' : 'BMD',
'Bhutan' : 'BTN',
'Bolivia' : 'BOB',
'Bonaire' : 'USD',
'Bosnia and Herzegovina' : 'BAM',
'Botswana' : 'BWP',
'Brazil' : 'BRL',
'British Indian Ocean Ter' : 'USD',
'British Virgin Islands' : 'USD',
'Brunei Darussalam' : 'BND',
'Bulgaria' : 'BGN',
'Burkina Faso' : 'XOF',
'Burundi' : 'BIF',
'Cabo Verde' : 'CVE',
'Cambodia' : 'KHR',
'Cameroon' : 'XAF',
'Canada' : 'CAD',
'Cayman Islands' : 'KYD',
'Central African Republic' : 'XAF',
'Chad' : 'XAF',
'Channel Islands' : 'GBP',
'Chile' : 'CLP',
'China' : 'CNY',
'China, Hong Kong SAR' : 'HKD',
'China, Macao SAR'  : 'MOP',
'Taiwan Province of China' : 'TWD',
'Christmas Island' : 'AUD',
'Cocos (Keeling) Islands' : 'AUD',
'Colombia' : 'COP',
'Comoros' : 'KMF',
'Congo' : 'XAF',
'Congo, Dem. Rep. of the Congolese' : 'CDF',
'Cook Islands' : 'NZD',
'Costa Rica' : 'CRC',
'Côte dIvoire' : 'XOF',
'Croatia' : 'HRK',
'Cuba' : 'CUP',
'Curaçao' : 'ANG',
'Cyprus' : 'EUR',
'Czechia' : 'CZK',
'Denmark' : 'DKK',
'Djibouti' : 'DJF',
'Dominica' : 'XCD',
'Dominican Republic' : 'DOP',
'Ecuador' : 'USD',
'Egypt' : 'EGP',
'El Salvador' : 'USD',
'Equatorial Guinea' : 'XAF',
'Eritrea' : 'ERN',
'Estonia' : 'EUR',
'Ethiopia' : 'ETB',
'Falkland Is.(Malvinas)' : 'FKP',
'Faroe Islands' : 'DKK',
'Fiji, Republic of Fiji' : 'FJD',
'Finland' : 'EUR',
'France' : 'EUR',
'French Guiana' : 'EUR',
'French Polynesia' : 'XPF',
'French Southern Terr' : 'EUR',
'Gabon' : 'XAF',
'Gambia' : 'GMD',
'Georgia' : 'GEL',
'Germany' : 'EUR',
'Ghana' : 'GHS',
'Gibraltar' : 'GIP',
'Greece' : 'EUR',
'Greenland' : 'DKK',
'Grenada' : 'XCD',
'Guadeloupe' : 'EUR',
'Guam' : 'USD',
'Guatemala' : 'GTQ',
'Guernsey' : 'GBP',
'Guinea' : 'GNF',
'Guinea-Bissau' : 'XOF',
'Guyana' : 'GYD',
'Haiti' : 'HTG',
'Honduras' : 'HNL',
'Hungary' : 'HUF',
'Iceland' : 'ISK',
'India' : 'INR',
'Indonesia' : 'IDR',
'Iran (Islamic Rep of )' : 'IRR',
'Iraq' : 'IQD',
'Ireland' : 'EUR',
'Isle of Man Pound' : 'GBP',
'Israel' : 'ILS',
'Italy' : 'EUR',
'Jamaica' : 'JMD',
'Japan' : 'JPY',
'Jersey' : 'GBP',
'Jordan' : 'JOD',
'Kazakhstan' : 'KZT',
'Kenya' : 'KES',
'Kiribati' : 'AUD',
'Korea Dem Peoples Rep North Korean' : 'KPW',
'Korea Republic of' : 'KRW',
'Kuwait' : 'KWD',
'Kyrgyzstan' : 'KGS',
'Lao Peoples Dem Rep' : 'LAK',
'Latvia' : 'EUR',
'Lebanon' : 'LBP',
'Lesotho' : 'LSL',
'Liberia' : 'LRD',
'Libya' : 'LYD',
'Liechtenstein' : 'CHF',
'Lithuania' : 'EUR',
'Luxembourg' : 'EUR',
'Macedonia Fmr Yug Rp of' : 'MKD',
'Madagascar' : 'MGA',
'Malawi' : 'MWK',
'Malaysia' : 'MYR',
'Maldives' : 'MVR',
'Mali' : 'XOF',
'Malta' : 'EUR',
'Marshall Islands' : 'USD',
'Martinique' : 'EUR',
'Mauritania' : 'MRO',
'Mauritius' : 'MUR',
'Mayotte' : 'EUR',
'Mexico' : 'MXN',
'Micronesia Fed States of' : 'USD',
'Moldova Republic of' : 'MDL',
'Mongolia' : 'MNT',
'Montenegro' : 'EUR',
'Montserrat' : 'XCD',
'Morocco' : 'MAD',
'Mozambique' : 'MZN',
'Myanmar' : 'MMK',
'Namibia' : 'NAD',
'Nauru' : 'AUD',
'Nepal' : 'NPR',
'Netherlands' : 'EUR',
'New Caledonia' : 'XPF',
'New Zealand' : 'NZD',
'Nicaragua' : 'NIO',
'Niger' : 'XOF',
'Nigeria' : 'NGN',
'Niue' : 'NZD',
'Northern Mariana Is' : 'USD',
'Norway' : 'NOK',
'Oman' : 'OMR',
'Pakistan' : 'PKR',
'Palau' : 'USD',
'Panama' : 'PAB',
'Papua New Guinea' : 'PGK',
'Paraguay' : 'PYG',
'Peru' : 'PEN',
'Philippines' : 'PHP',
'Pitcairn Islands' : 'NZD',
'Poland' : 'PLN',
'Portugal' : 'EUR',
'Puerto Rico' : 'USD',
'Qatar' : 'QAR',
'Réunion' : 'EUR',
'Romania' : 'RON',
'Russian Federation' : 'RUB',
'Rwanda' : 'RWF',
'Saint Barthélemy' : 'EUR',
'Saint Helena' : 'SHP',
'Saint Kitts and Nevis' : 'XCD',
'Saint Lucia' : 'XCD',
'Saint-Martin' : 'EUR',
'St Pierre and Miquelon' : 'EUR',
'Saint Vincent/Grenadines' : 'XCD',
'Samoa' : 'WST',
'Sao Tome and Principe' : 'STD',
'Saudi Arabia' : 'SAR',
'Senegal' : 'XOF',
'Serbia' : 'RSD',
'Seychelles' : 'SCR',
'Sierra Leone' : 'SLL',
'Singapore' : 'SGD',
'Sint Maarten' : 'ANG',
'Slovakia' : 'EUR',
'Slovenia' : 'EUR',
'Solomon Islands' : 'SBD',
'Somalia' : 'SOS',
'South Africa' : 'ZAR',
'South Sudan' : 'SSP',
'Spain' : 'EUR',
'Sri Lanka' : 'LKR',
'Sudan' : 'SDG',
'Suriname' : 'SRD',
'Swaziland' : 'SZL',
'Sweden' : 'SEK',
'Switzerland' : 'CHF',
'Syrian Arab Republic' : 'SYP',
'Tajikistan' : 'TJS',
'Tanzania United Rep of' : 'TZS',
'Thailand' : 'THB',
'Timor-Leste' : 'USD',
'Togo' : 'XOF',
'Tokelau' : 'NZD',
'Tonga' : 'TOP',
'Trinidad and Tobago' : 'TTD',
'Tunisia' : 'TND',
'Turkey' : 'TRY',
'Turkmenistan' : 'TMT',
'Turks and Caicos Is' : 'USD',
'Tuvalu' : 'AUD',
'Uganda' : 'UGX',
'Ukraine' : 'UAH',
'United Arab Emirates' : 'AED',
'United Kingdom' : 'GBP',
'United States of America' : 'USD',
'US Virgin Islands' : 'USD',
'Uruguay' : 'UYU',
'Uzbekistan' : 'UZS',
'Vanuatu' : 'VUV',
'Venezuela Boliv Rep of' : 'VEF',
'Viet Nam' : 'VND',
'Wallis and Futuna Is' : 'XPF',
'Western Sahara' : 'MAD',
'Yemen' : 'YER',
'Zambia' : 'ZMW',
'Zimbabwe' : 'ZWL'
}
def id(str):
    return dict[str]
