# Generated by Django 3.2.16 on 2022-12-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('plank', '0013_rename_lending_user_checkoutprocess_lending_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.site'),
        ),
    ]
