# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


class RequiredGetNationalIdResponseEntity(TypedDict):
    pass

class OptionalGetNationalIdResponseEntity(TypedDict, total=False):
    date_of_birth: str

    first_name: str

    gender: str

    id: str

    is_date_of_birth_match: bool

    is_first_name_match: bool

    is_gender_match: bool

    is_last_name_match: bool

    is_middle_name_match: bool

    last_name: str

    middle_name: str

class GetNationalIdResponseEntity(RequiredGetNationalIdResponseEntity, OptionalGetNationalIdResponseEntity):
    pass
