# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from dojah_client.type.kyc_submit_address_response_entity_data import KycSubmitAddressResponseEntityData

class RequiredKycSubmitAddressResponseEntity(TypedDict):
    pass

class OptionalKycSubmitAddressResponseEntity(TypedDict, total=False):
    status: typing.Union[int, float]

    reference_id: str

    data: KycSubmitAddressResponseEntityData

class KycSubmitAddressResponseEntity(RequiredKycSubmitAddressResponseEntity, OptionalKycSubmitAddressResponseEntity):
    pass
