# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from dojah_client.type.verify_selfie_bvn_response_entity_selfie_verification import VerifySelfieBvnResponseEntitySelfieVerification

class RequiredVerifySelfieBvnResponseEntity(TypedDict):
    pass

class OptionalVerifySelfieBvnResponseEntity(TypedDict, total=False):
    bvn: str

    date_of_birth: str

    email: str

    enrollment_bank: str

    enrollment_branch: str

    first_name: str

    gender: str

    image: str

    last_name: str

    level_of_account: str

    lga_of_origin: str

    lga_of_residence: str

    marital_status: str

    middle_name: str

    name_on_card: str

    nin: str

    phone_number1: str

    phone_number2: str

    registration_date: str

    residential_address: str

    selfie_verification: VerifySelfieBvnResponseEntitySelfieVerification

    state_of_origin: str

    state_of_residence: str

    watch_listed: str

class VerifySelfieBvnResponseEntity(RequiredVerifySelfieBvnResponseEntity, OptionalVerifySelfieBvnResponseEntity):
    pass
