# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from dojah_client.type.analyze_document_response_entity_document_images import AnalyzeDocumentResponseEntityDocumentImages
from dojah_client.type.analyze_document_response_entity_document_type import AnalyzeDocumentResponseEntityDocumentType
from dojah_client.type.analyze_document_response_entity_status import AnalyzeDocumentResponseEntityStatus
from dojah_client.type.analyze_document_response_entity_text_data import AnalyzeDocumentResponseEntityTextData

class RequiredAnalyzeDocumentResponseEntity(TypedDict):
    pass

class OptionalAnalyzeDocumentResponseEntity(TypedDict, total=False):
    document_images: AnalyzeDocumentResponseEntityDocumentImages

    document_type: AnalyzeDocumentResponseEntityDocumentType

    status: AnalyzeDocumentResponseEntityStatus

    text_data: AnalyzeDocumentResponseEntityTextData

class AnalyzeDocumentResponseEntity(RequiredAnalyzeDocumentResponseEntity, OptionalAnalyzeDocumentResponseEntity):
    pass
