# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from dojah_client.type.fraud_get_ip_reputation_response_entity_report import FraudGetIpReputationResponseEntityReport

class RequiredFraudGetIpReputationResponseEntity(TypedDict):
    pass

class OptionalFraudGetIpReputationResponseEntity(TypedDict, total=False):
    report: FraudGetIpReputationResponseEntityReport

    success: bool

class FraudGetIpReputationResponseEntity(RequiredFraudGetIpReputationResponseEntity, OptionalFraudGetIpReputationResponseEntity):
    pass
