# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from dojah_client.type.fraud_get_email_reputation_response_entity_breach_details_breaches import FraudGetEmailReputationResponseEntityBreachDetailsBreaches

class RequiredFraudGetEmailReputationResponseEntityBreachDetails(TypedDict):
    pass

class OptionalFraudGetEmailReputationResponseEntityBreachDetails(TypedDict, total=False):
    haveibeenpwned_listed: bool

    number_of_breaches: typing.Union[int, float]

    first_breach: typing.Optional[str]

    breaches: FraudGetEmailReputationResponseEntityBreachDetailsBreaches

class FraudGetEmailReputationResponseEntityBreachDetails(RequiredFraudGetEmailReputationResponseEntityBreachDetails, OptionalFraudGetEmailReputationResponseEntityBreachDetails):
    pass
