# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from dojah_client.type.fraud_screen_user_response_entity_email_check_result import FraudScreenUserResponseEntityEmailCheckResult
from dojah_client.type.fraud_screen_user_response_entity_ip_check_result import FraudScreenUserResponseEntityIpCheckResult
from dojah_client.type.fraud_screen_user_response_entity_phone_check_result import FraudScreenUserResponseEntityPhoneCheckResult

class RequiredFraudScreenUserResponseEntity(TypedDict):
    pass

class OptionalFraudScreenUserResponseEntity(TypedDict, total=False):
    aml_screening_result: typing.Optional[str]

    ip_check_result: FraudScreenUserResponseEntityIpCheckResult

    email_check_result: FraudScreenUserResponseEntityEmailCheckResult

    phone_check_result: FraudScreenUserResponseEntityPhoneCheckResult

    overall_risk_score: typing.Union[int, float]

class FraudScreenUserResponseEntity(RequiredFraudScreenUserResponseEntity, OptionalFraudScreenUserResponseEntity):
    pass
