# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chainmaker.protos.accesscontrol import member_pb2 as accesscontrol_dot_member__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ommon/request.proto\x12\x06\x63ommon\x1a\x1a\x61\x63\x63\x65sscontrol/member.proto\"\xad\x01\n\tTxRequest\x12 \n\x07payload\x18\x01 \x01(\x0b\x32\x0f.common.Payload\x12(\n\x06sender\x18\x02 \x01(\x0b\x32\x18.common.EndorsementEntry\x12+\n\tendorsers\x18\x03 \x03(\x0b\x32\x18.common.EndorsementEntry\x12\'\n\x05payer\x18\x04 \x01(\x0b\x32\x18.common.EndorsementEntry\"\x1d\n\x0cRawTxRequest\x12\r\n\x05rawTx\x18\x01 \x01(\x0c\"\xf8\x01\n\x07Payload\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\t\x12\x1f\n\x07tx_type\x18\x02 \x01(\x0e\x32\x0e.common.TxType\x12\r\n\x05tx_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x17\n\x0f\x65xpiration_time\x18\x05 \x01(\x03\x12\x15\n\rcontract_name\x18\x06 \x01(\t\x12\x0e\n\x06method\x18\x07 \x01(\t\x12(\n\nparameters\x18\x08 \x03(\x0b\x32\x14.common.KeyValuePair\x12\x10\n\x08sequence\x18\t \x01(\x04\x12\x1c\n\x05limit\x18\n \x01(\x0b\x32\r.common.Limit\"L\n\x10\x45ndorsementEntry\x12%\n\x06signer\x18\x01 \x01(\x0b\x32\x15.accesscontrol.Member\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1a\n\x05Limit\x12\x11\n\tgas_limit\x18\x01 \x01(\x04*M\n\x06TxType\x12\x13\n\x0fINVOKE_CONTRACT\x10\x00\x12\x12\n\x0eQUERY_CONTRACT\x10\x01\x12\r\n\tSUBSCRIBE\x10\x02\x12\x0b\n\x07\x41RCHIVE\x10\x03\x42\x45\n\x18org.chainmaker.pb.commonZ)chainmaker.org/chainmaker/pb-go/v2/commonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.chainmaker.pb.commonZ)chainmaker.org/chainmaker/pb-go/v2/common'
  _TXTYPE._serialized_start=668
  _TXTYPE._serialized_end=745
  _TXREQUEST._serialized_start=61
  _TXREQUEST._serialized_end=234
  _RAWTXREQUEST._serialized_start=236
  _RAWTXREQUEST._serialized_end=265
  _PAYLOAD._serialized_start=268
  _PAYLOAD._serialized_end=516
  _ENDORSEMENTENTRY._serialized_start=518
  _ENDORSEMENTENTRY._serialized_end=594
  _KEYVALUEPAIR._serialized_start=596
  _KEYVALUEPAIR._serialized_end=638
  _LIMIT._serialized_start=640
  _LIMIT._serialized_end=666
# @@protoc_insertion_point(module_scope)
