# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .dictionary_classifier_response import DictionaryClassifierResponse
from .proprietary_classifier_response import ProprietaryClassifierResponse
from .regex_classifier_response import RegexClassifierResponse


class ClassAndClassifierConfigSchemaClassifierConfig_Proprietary(ProprietaryClassifierResponse):
    method: typing_extensions.Literal["PROPRIETARY"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ClassAndClassifierConfigSchemaClassifierConfig_Regex(RegexClassifierResponse):
    method: typing_extensions.Literal["REGEX"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ClassAndClassifierConfigSchemaClassifierConfig_Dictionary(DictionaryClassifierResponse):
    method: typing_extensions.Literal["DICTIONARY"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


ClassAndClassifierConfigSchemaClassifierConfig = typing.Union[
    ClassAndClassifierConfigSchemaClassifierConfig_Proprietary,
    ClassAndClassifierConfigSchemaClassifierConfig_Regex,
    ClassAndClassifierConfigSchemaClassifierConfig_Dictionary,
]
