
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-31T13:41:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "50a29fc46c7d6236609dd3ac38fee01a5031ee88",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
