
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-02T13:17:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "796c1b34a525c42b38a9822e1ecd6b7257dbb466",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
