
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-02T09:39:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b589b786004bfc2cdc54e2f871042609b12b5d7",
 "version": "0.7.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
