# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .rerank_response_meta import RerankResponseMeta
from .rerank_response_results_item import RerankResponseResultsItem


class RerankResponse(pydantic.BaseModel):
    id: typing.Optional[str]
    results: typing.List[RerankResponseResultsItem] = pydantic.Field(
        description=("An ordered list of ranked documents\n")
    )
    meta: typing.Optional[RerankResponseMeta]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
