# Generated by Django 4.2.3 on 2023-08-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_leaflet', '0002_auto_20200310_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='location_search_term',
            field=models.CharField(
                blank=True,
                help_text=
                'Instead of coordinates you can enter the address or a search term, and Nominatim will try to look up the location. The first hit of the list will be used.',
                max_length=100,
                verbose_name='location search term'
            ),
        ),
        migrations.AddField(
            model_name='marker',
            name='location_search_term',
            field=models.CharField(
                blank=True,
                help_text=
                'Instead of coordinates you can enter the address or a search term, and Nominatim will try to look up the location. The first hit of the list will be used.',
                max_length=100,
                verbose_name='location search term'
            ),
        ),
        migrations.AlterField(
            model_name='map',
            name='cmsplugin_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='%(app_label)s_%(class)s',
                serialize=False,
                to='cms.cmsplugin'
            ),
        ),
        migrations.AlterField(
            model_name='map',
            name='latitude',
            field=models.FloatField(
                blank=True, help_text='in °', verbose_name='latitude'
            ),
        ),
        migrations.AlterField(
            model_name='map',
            name='longitude',
            field=models.FloatField(
                blank=True, help_text='in °', verbose_name='longitude'
            ),
        ),
        migrations.AlterField(
            model_name='marker',
            name='cmsplugin_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='%(app_label)s_%(class)s',
                serialize=False,
                to='cms.cmsplugin'
            ),
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(blank=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(
                blank=True,
                help_text=
                'If you enter both latitude and longitude, these data won’t be overridden by a geocoding lookup.',
                verbose_name='longitude'
            ),
        ),
    ]
