# coding: utf-8

"""
    DOJAH Publilc APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dojah_client.paths.api_v1_ml_liveness.post import CheckLiveness
from dojah_client.paths.api_v1_kyc_accounts.get import GetAccounts
from dojah_client.paths.api_v1_kyc_address.get import GetAddressVerification
from dojah_client.paths.api_v1_kyc_nuban_bvn.get import GetBvnFromNuban
from dojah_client.paths.api_v1_kyc_vin.get import GetVin
from dojah_client.paths.api_v1_kyc_address.post import SubmitAddress


class KYCApi(
    CheckLiveness,
    GetAccounts,
    GetAddressVerification,
    GetBvnFromNuban,
    GetVin,
    SubmitAddress,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
