# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drift_protocol/trigger_service/interval_trigger_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='drift_protocol/trigger_service/interval_trigger_message.proto',
  package='drift.proto.trigger_service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=drift_protocol/trigger_service/interval_trigger_message.proto\x12\x1b\x64rift.proto.trigger_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n\x16IntervalTriggerMessage\x12\x33\n\x0fstart_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0estop_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x01\x10\x02\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_INTERVALTRIGGERMESSAGE = _descriptor.Descriptor(
  name='IntervalTriggerMessage',
  full_name='drift.proto.trigger_service.IntervalTriggerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='drift.proto.trigger_service.IntervalTriggerMessage.start_timestamp', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop_timestamp', full_name='drift.proto.trigger_service.IntervalTriggerMessage.stop_timestamp', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=263,
)

_INTERVALTRIGGERMESSAGE.fields_by_name['start_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_INTERVALTRIGGERMESSAGE.fields_by_name['stop_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['IntervalTriggerMessage'] = _INTERVALTRIGGERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntervalTriggerMessage = _reflection.GeneratedProtocolMessageType('IntervalTriggerMessage', (_message.Message,), {
  'DESCRIPTOR' : _INTERVALTRIGGERMESSAGE,
  '__module__' : 'drift_protocol.trigger_service.interval_trigger_message_pb2'
  # @@protoc_insertion_point(class_scope:drift.proto.trigger_service.IntervalTriggerMessage)
  })
_sym_db.RegisterMessage(IntervalTriggerMessage)


# @@protoc_insertion_point(module_scope)
