CACHE_SIZE = 256

NAMED_REGEX = r':[\w|\d]*'

MYSQL, POSTGRESQL, ORACLE, SQL_SERVER, SQLITE, UNKNOW = 'MySQL', 'PostgreSQL', 'Oracle', 'SQL Server', 'SQLite', 'Unknow'

MYSQLCLIENT, PYMYSQL, MYSQL_CONNECTOR, PSYCOPG2, PG8000, ORACLEDB, SQLITE3 = 'MySQLdb', 'pymysql', 'mysql.connector', 'psycopg2', 'pg8000', 'oracledb', 'sqlite3'

DRIVERS = {MYSQLCLIENT: MYSQL, PYMYSQL: MYSQL, MYSQL_CONNECTOR: MYSQL, PSYCOPG2: POSTGRESQL, PG8000: POSTGRESQL, ORACLEDB: ORACLE, SQLITE3: SQLITE}
