## cli keyword
PIPELINE = 'pipeline'
RETRIEVAL = 'retrieval'
READER = 'reader'
DATA = 'data'
PATH_TRAIN = 'path_train'
PATH_EVALUATOR = 'path_evaluator'
CONFIG_DATA = 'config_data'
PARAMETERS = 'parameters'
NAME = 'name'
LOSS_FN = 'loss_fn'
MODEL = 'model'
SAVE_LOG = 'save_log'
PATH_SAVE_LOG = 'path_save_log'
TOP_K_QA = 'top_k_qa'
IS_TRAIN = 'is_train'

RANDOM = 'random'
BM25 = 'bm25'
SBERT = 'sbert'
TRIPLET = 'triplet'
PAIR = 'pair'
CONTEXT = 'context'
QAS = 'qas'
QUESTION = 'question'
ANSWER = 'answer'
ANSWERS = 'answers'
TEXT = 'text'
CONTEXT_KEY = 'context_key'
QAS_KEY = 'qas_key'
QUESTION_KEY = 'question_key'
ANSWER_WORD_START_IDX = 'answer_word_start_idx'
ANSWER_WORD_END_IDX = 'answer_word_end_idx'
ANSWERS_KEY = 'answers_key'
ANSWER_KEY = 'answer_key'
WORDS_LENGTH = 'words_length'
SPAN_ANSWER_IDS = 'span_answer_ids'
ANSWER_START = 'answer_start'
MAX_LENGTH = 'max_length'
MAX_LENGTH_DOCUMENT = 'max_length_document'
OVER_LAPPING_SIZE = 'over_lapping_size'
IS_VALID = 'id_valid'
NUM_PROC = 'num_proc'
FOLDER_QA_SAVE = 'folder_qa_save'

INFER_MODE = 'infer_mode'
MODE_CHUNKING = 'mode_chunking'
IS_VNSQUAD_EVAL = 'is_vnsquad_eval'
TOP_K_BM25 = 'top_k_bm25'
TOP_K_SBERT = 'top_k_sbert'
GET_SCORE = 'get_score'
EMBEDDING_SCORE = 'embedding_score'
COMBINE_BM25_EMBED_SCORE = 'combine_bm25_embed_score'
IS_DOCUMENT_RIGHT = 'is_document_right'

## QA INPUT
ATTENTION_MASK = 'attention_mask'
INPUT_IDS = 'input_ids'
OFFSET_MAPPING = 'offset_mapping'
START_IDX = 'start_idx'
END_IDX = 'end_idx'
PRETRAINED_QA = 'pretrained_qa'
MODEL_NAME_OR_PATH ='model_name_or_path'

##  Hyperparameter
OUTPUT_DIR = 'output_dir'
OVERWRITE_OUTPUT_DIR = 'overwrite_output_dir'
DO_TRANING = 'do_training'
DO_EVAL = 'do_eval'
NUM_TRAIN_EPOCHS = 'num_train_epochs'
LEARNING_RATE = 'learning_rate'
WARMPUP_RATIO = 'warpup_ratio'
WEIGHT_DECAY = 'weight_decay'
PER_DEVICE_TRANING_BATCH_SIZE = 'per_device_training_batch_size'
PER_DEVICE_EVAL_BATCH_SIZE = 'per_device_eval_batch_size'
GRADIENT_ACCUMULATION_STEPS = 'gradient_accumulation_steps'
LOGGING_DIR = 'logging_dir'
LOGGING_STEP = 'logging_step'
LABEL_NAMES = 'label_names'
SAVE_STRATEGY = 'save_strategy'
METRIC_FOR_BEST_MODEL = 'metric_for_best_model'
LOAD_BEST_MODEL_AT_END = 'load_best_model_at_end'
SAVE_TOTAL_LIMIT = 'save_total_limit'
EVALUATION_STRATEGY = 'evaluation_strategy'
LOGGING_STRATEGY = 'logging_strategy'
BATCH_SIZE_TRAINING = 'batch_size_training'
BATCH_SIZE_EVAL = 'batch_size_eval'
BATCH_SIZE = 'batch_size'
EPOCHS = 'epochs'
MAKE_NEGATIVE_MRC = 'make_negative_mrc'
N_NEGATIVE_MRC = 'n_negative_mrc'
IS_NEGATIVE_SAMPLE = 'is_negative_sample'
DATA_ARGUMENT = 'data_argument'
LAMBDA_WEIGHT = 'lambda_weight'
THRESHOLD_SAMPLING = 'threshold_sampling'




