VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('30')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('56')
MAJOR_VERSION = 4
MINOR_VERSION = 16
PATCH_VERSION = 202307300756
version_date = '2023/07/30 07:56'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
