# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .similar_assets_alert_content import SimilarAssetsAlertContent
from .violated_iam_group_alert_content import ViolatedIamGroupAlertContent
from .violated_iam_role_alert_content import ViolatedIamRoleAlertContent
from .violated_identity_alert_content import ViolatedIdentityAlertContent
from .violated_store_alert_content import ViolatedStoreAlertContent


class AlertResponseSchemaContent_ViolatedStore(ViolatedStoreAlertContent):
    type: typing_extensions.Literal["VIOLATED_STORE"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class AlertResponseSchemaContent_SimilarAssets(SimilarAssetsAlertContent):
    type: typing_extensions.Literal["SIMILAR_ASSETS"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class AlertResponseSchemaContent_ViolatedIdentity(ViolatedIdentityAlertContent):
    type: typing_extensions.Literal["VIOLATED_IDENTITY"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class AlertResponseSchemaContent_ViolatedIamGroup(ViolatedIamGroupAlertContent):
    type: typing_extensions.Literal["VIOLATED_IAM_GROUP"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class AlertResponseSchemaContent_ViolatedIamRole(ViolatedIamRoleAlertContent):
    type: typing_extensions.Literal["VIOLATED_IAM_ROLE"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


AlertResponseSchemaContent = typing.Union[
    AlertResponseSchemaContent_ViolatedStore,
    AlertResponseSchemaContent_SimilarAssets,
    AlertResponseSchemaContent_ViolatedIdentity,
    AlertResponseSchemaContent_ViolatedIamGroup,
    AlertResponseSchemaContent_ViolatedIamRole,
]
