# This file was auto-generated by Fern from our API Definition.

import typing

from .grouped_data_table_result import GroupedDataTableResult
from .list_all_assets_response import ListAllAssetsResponse

GetAllApiV2DataAssetsGetResponse = typing.Union[ListAllAssetsResponse, GroupedDataTableResult]
