# This file was auto-generated by Fern from our API Definition.

import typing

from .grouped_data_table_result import GroupedDataTableResult
from .list_all_policies_response import ListAllPoliciesResponse

GetAllApiV2PoliciesGetResponse = typing.Union[ListAllPoliciesResponse, GroupedDataTableResult]
