
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-28T06:10:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbd7d14d8180db5fa77eca94e06133ebcbf3d442",
 "version": "2023.7.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
