
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-30T11:41:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "72454fff50572974a1d2d6be0fc6db3988970bcf",
 "version": "2.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
