
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-31T06:45:19-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "4b48137e59ecc3dd61a89a03a1f3c759e775670a",
 "version": "0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
