# This file was auto-generated by Fern from our API Definition.

import typing

from .connector_input import ConnectorInput

CreateApiV2ConnectorsPostRequest = typing.Union[ConnectorInput, typing.List[ConnectorInput]]
