"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.discovery.v0.discoveryapplication_pb2
import grpc

class DiscoveryApplicationStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    RunScriptFile: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptFileRequest,
        ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptFileResponse] = ...
    """Runs a script based on a file."""

    RunScript: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptRequest,
        ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptResponse] = ...
    """Runs a script based on a supplied string."""

    RunCommand: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.discoveryapplication_pb2.RunCommandRequest,
        ansys.api.discovery.v0.discoveryapplication_pb2.RunCommandResponse] = ...
    """Runs a command. A command can be exposed by Addin."""


class DiscoveryApplicationServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def RunScriptFile(self,
        request: ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptFileRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptFileResponse:
        """Runs a script based on a file."""
        pass

    @abc.abstractmethod
    def RunScript(self,
        request: ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoveryapplication_pb2.RunScriptResponse:
        """Runs a script based on a supplied string."""
        pass

    @abc.abstractmethod
    def RunCommand(self,
        request: ansys.api.discovery.v0.discoveryapplication_pb2.RunCommandRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.discoveryapplication_pb2.RunCommandResponse:
        """Runs a command. A command can be exposed by Addin."""
        pass


def add_DiscoveryApplicationServicer_to_server(servicer: DiscoveryApplicationServicer, server: grpc.Server) -> None: ...
