"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.discovery.v0.datamodels_pb2
import ansys.api.discovery.v0.documents_pb2
import google.protobuf.empty_pb2
import grpc

class DocumentsStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        ansys.api.discovery.v0.datamodels_pb2.Document] = ...

    Open: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.documents_pb2.OpenRequest,
        ansys.api.discovery.v0.datamodels_pb2.EntityIdentifier] = ...

    New: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.documents_pb2.NewRequest,
        ansys.api.discovery.v0.datamodels_pb2.Document] = ...

    Close: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        google.protobuf.empty_pb2.Empty] = ...

    Save: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        google.protobuf.empty_pb2.Empty] = ...

    SaveAs: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.documents_pb2.SaveAsRequest,
        ansys.api.discovery.v0.datamodels_pb2.EntityIdentifier] = ...

    Insert: grpc.UnaryUnaryMultiCallable[
        ansys.api.discovery.v0.documents_pb2.InsertRequest,
        ansys.api.discovery.v0.datamodels_pb2.EntityIdentifier] = ...


class DocumentsServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.datamodels_pb2.Document: ...

    @abc.abstractmethod
    def Open(self,
        request: ansys.api.discovery.v0.documents_pb2.OpenRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.datamodels_pb2.EntityIdentifier: ...

    @abc.abstractmethod
    def New(self,
        request: ansys.api.discovery.v0.documents_pb2.NewRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.datamodels_pb2.Document: ...

    @abc.abstractmethod
    def Close(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...

    @abc.abstractmethod
    def Save(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...

    @abc.abstractmethod
    def SaveAs(self,
        request: ansys.api.discovery.v0.documents_pb2.SaveAsRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.datamodels_pb2.EntityIdentifier: ...

    @abc.abstractmethod
    def Insert(self,
        request: ansys.api.discovery.v0.documents_pb2.InsertRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.discovery.v0.datamodels_pb2.EntityIdentifier: ...


def add_DocumentsServicer_to_server(servicer: DocumentsServicer, server: grpc.Server) -> None: ...
