# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/discovery/v0/documents.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.discovery.v0 import datamodels_pb2 as ansys_dot_api_dot_discovery_dot_v0_dot_datamodels__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ansys/api/discovery/v0/documents.proto\x12 ansys.api.discovery.v0.Documents\x1a\'ansys/api/discovery/v0/datamodels.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x0eGetAllResponse\x12\x31\n\x07\x64\x65signs\x18\x01 \x03(\x0b\x32 .ansys.api.discovery.v0.Document\"\x1f\n\x0bOpenRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"\x1a\n\nNewRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rSaveAsRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"!\n\rInsertRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t2\xbf\x04\n\tDocuments\x12?\n\x03Get\x12\x16.google.protobuf.Empty\x1a .ansys.api.discovery.v0.Document\x12_\n\x04Open\x12-.ansys.api.discovery.v0.Documents.OpenRequest\x1a(.ansys.api.discovery.v0.EntityIdentifier\x12U\n\x03New\x12,.ansys.api.discovery.v0.Documents.NewRequest\x1a .ansys.api.discovery.v0.Document\x12\x37\n\x05\x43lose\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x36\n\x04Save\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x63\n\x06SaveAs\x12/.ansys.api.discovery.v0.Documents.SaveAsRequest\x1a(.ansys.api.discovery.v0.EntityIdentifier\x12\x63\n\x06Insert\x12/.ansys.api.discovery.v0.Documents.InsertRequest\x1a(.ansys.api.discovery.v0.EntityIdentifierB#\xaa\x02 Ansys.Api.Discovery.V0.Documentsb\x06proto3')



_GETALLRESPONSE = DESCRIPTOR.message_types_by_name['GetAllResponse']
_OPENREQUEST = DESCRIPTOR.message_types_by_name['OpenRequest']
_NEWREQUEST = DESCRIPTOR.message_types_by_name['NewRequest']
_SAVEASREQUEST = DESCRIPTOR.message_types_by_name['SaveAsRequest']
_INSERTREQUEST = DESCRIPTOR.message_types_by_name['InsertRequest']
GetAllResponse = _reflection.GeneratedProtocolMessageType('GetAllResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLRESPONSE,
  '__module__' : 'ansys.api.discovery.v0.documents_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.Documents.GetAllResponse)
  })
_sym_db.RegisterMessage(GetAllResponse)

OpenRequest = _reflection.GeneratedProtocolMessageType('OpenRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENREQUEST,
  '__module__' : 'ansys.api.discovery.v0.documents_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.Documents.OpenRequest)
  })
_sym_db.RegisterMessage(OpenRequest)

NewRequest = _reflection.GeneratedProtocolMessageType('NewRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWREQUEST,
  '__module__' : 'ansys.api.discovery.v0.documents_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.Documents.NewRequest)
  })
_sym_db.RegisterMessage(NewRequest)

SaveAsRequest = _reflection.GeneratedProtocolMessageType('SaveAsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEASREQUEST,
  '__module__' : 'ansys.api.discovery.v0.documents_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.Documents.SaveAsRequest)
  })
_sym_db.RegisterMessage(SaveAsRequest)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'ansys.api.discovery.v0.documents_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.Documents.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

_DOCUMENTS = DESCRIPTOR.services_by_name['Documents']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002 Ansys.Api.Discovery.V0.Documents'
  _GETALLRESPONSE._serialized_start=146
  _GETALLRESPONSE._serialized_end=213
  _OPENREQUEST._serialized_start=215
  _OPENREQUEST._serialized_end=246
  _NEWREQUEST._serialized_start=248
  _NEWREQUEST._serialized_end=274
  _SAVEASREQUEST._serialized_start=276
  _SAVEASREQUEST._serialized_end=309
  _INSERTREQUEST._serialized_start=311
  _INSERTREQUEST._serialized_end=344
  _DOCUMENTS._serialized_start=347
  _DOCUMENTS._serialized_end=922
# @@protoc_insertion_point(module_scope)
