# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/discovery/v0/drivingdimensions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.discovery.v0 import datamodels_pb2 as ansys_dot_api_dot_discovery_dot_v0_dot_datamodels__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ansys/api/discovery/v0/drivingdimensions.proto\x12(ansys.api.discovery.v0.DrivingDimensions\x1a\'ansys/api/discovery/v0/datamodels.proto\"\x1f\n\rGetAllRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\"V\n\x0eGetAllResponse\x12\x44\n\x12\x64riving_dimensions\x18\x01 \x03(\x0b\x32(.ansys.api.discovery.v0.DrivingDimension\"T\n\rUpdateRequest\x12\x43\n\x11\x64riving_dimension\x18\x01 \x01(\x0b\x32(.ansys.api.discovery.v0.DrivingDimension2\xd8\x02\n\x11\x44rivingDimensions\x12Y\n\x03Get\x12(.ansys.api.discovery.v0.EntityIdentifier\x1a(.ansys.api.discovery.v0.DrivingDimension\x12{\n\x06GetAll\x12\x37.ansys.api.discovery.v0.DrivingDimensions.GetAllRequest\x1a\x38.ansys.api.discovery.v0.DrivingDimensions.GetAllResponse\x12k\n\x06Update\x12\x37.ansys.api.discovery.v0.DrivingDimensions.UpdateRequest\x1a(.ansys.api.discovery.v0.DrivingDimensionBCZ\x16\x61nsys/api/discovery/v0\xaa\x02(Ansys.Api.Discovery.V0.DrivingDimensionsb\x06proto3')



_GETALLREQUEST = DESCRIPTOR.message_types_by_name['GetAllRequest']
_GETALLRESPONSE = DESCRIPTOR.message_types_by_name['GetAllResponse']
_UPDATEREQUEST = DESCRIPTOR.message_types_by_name['UpdateRequest']
GetAllRequest = _reflection.GeneratedProtocolMessageType('GetAllRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLREQUEST,
  '__module__' : 'ansys.api.discovery.v0.drivingdimensions_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.DrivingDimensions.GetAllRequest)
  })
_sym_db.RegisterMessage(GetAllRequest)

GetAllResponse = _reflection.GeneratedProtocolMessageType('GetAllResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLRESPONSE,
  '__module__' : 'ansys.api.discovery.v0.drivingdimensions_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.DrivingDimensions.GetAllResponse)
  })
_sym_db.RegisterMessage(GetAllResponse)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'ansys.api.discovery.v0.drivingdimensions_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.discovery.v0.DrivingDimensions.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

_DRIVINGDIMENSIONS = DESCRIPTOR.services_by_name['DrivingDimensions']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026ansys/api/discovery/v0\252\002(Ansys.Api.Discovery.V0.DrivingDimensions'
  _GETALLREQUEST._serialized_start=133
  _GETALLREQUEST._serialized_end=164
  _GETALLRESPONSE._serialized_start=166
  _GETALLRESPONSE._serialized_end=252
  _UPDATEREQUEST._serialized_start=254
  _UPDATEREQUEST._serialized_end=338
  _DRIVINGDIMENSIONS._serialized_start=341
  _DRIVINGDIMENSIONS._serialized_end=685
# @@protoc_insertion_point(module_scope)
