# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class IdentityOrigin(str, enum.Enum):
    """
    An enumeration.
    """

    INTERNAL = "internal"
    EXTERNAL = "external"

    def visit(self, internal: typing.Callable[[], T_Result], external: typing.Callable[[], T_Result]) -> T_Result:
        if self is IdentityOrigin.INTERNAL:
            return internal()
        if self is IdentityOrigin.EXTERNAL:
            return external()
