# Generated by Django 4.0 on 2023-07-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit_trails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='actor',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
