// WebSocketMessageType
/* tslint:disable */

export enum WebSocketMessageType {
  HELLO = 'HELLO',
  CHAT_COMPLETE_REQUEST = 'CHAT_COMPLETE_REQUEST',
  CHAT_COMPLETE_RESPONSE = 'CHAT_COMPLETE_RESPONSE',
  CHAT_COMPLETE_ERROR = 'CHAT_COMPLETE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
