
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-28T18:44:09+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "53703c8b8adb5a5fd206649f061170e3a035dae5",
 "version": "1.2.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
