giphy = {
    'fuck_you': [
        'https://media.giphy.com/media/bOifD9wkVMRxu/giphy.gif',
        'https://media.giphy.com/media/TlyLGwSUSojn2/giphy.gif',
        'https://media.giphy.com/media/3oz8xRd39FNNdzZjGw/giphy.gif',
        'https://media.giphy.com/media/tfzw8nJe6FPFK/giphy.gif',
        'https://media.giphy.com/media/x1kS7NRIcIigU/giphy.gif',
        'https://media.giphy.com/media/26uf0bUZLbHRlsanS/giphy.gif',
        'https://media.giphy.com/media/26uf0bUZLbHRlsanS/giphy.gif',
        'https://media.giphy.com/media/3o6Zt21KAh2J70WGZ2/giphy.gif',
        'https://media.giphy.com/media/XHr6LfW6SmFa0/giphy.gif',
        'http://i.giphy.com/3haDutIDUeb8Q.gif',
        'https://media.giphy.com/media/QGzPdYCcBbbZm/giphy.gif',
        'https://media.giphy.com/media/ywtJsowFklRvO/giphy.gif',
        'https://media.giphy.com/media/8ogiX5AegMYwg/giphy.gif',
        'https://media.giphy.com/media/XHr6LfW6SmFa0/giphy.gif',
        'https://media.giphy.com/media/NBN2nFCVQDCDe/giphy.gif',
        'https://media.giphy.com/media/66r2Yxv4APr8Y/giphy.gif',
        'https://media.giphy.com/media/Vr9KXaqXsm4w0/giphy.gif',
        'https://media.giphy.com/media/KLhC7inqRb1za/giphy.gif',
        'https://media.giphy.com/media/Dp3CtzmXgFmlW/giphy.gif',
        'https://media.giphy.com/media/WfZscKZjc1ugg/giphy.gif',
        'https://media.giphy.com/media/Pwhl8lh703BzG/giphy.gif',
        'https://media.giphy.com/media/mADdmr45eBZHa/giphy.gif'
    ],
    'denied': [
        'https://media.giphy.com/media/4fNppUBK8Pv0s/giphy.gif',
        'https://media.giphy.com/media/l0MYMKA3VuMIobK2A/giphy.gif',
        'https://media.giphy.com/media/26u4m6DWqw4Zef38Y/giphy.gif',
        'https://media.giphy.com/media/4yh3ecEND3SwM/giphy.gif',
        'https://media.giphy.com/media/SQaBuN5Fw0AV2/giphy.gif',
        'https://media.giphy.com/media/c0q6VYTUSuUko/giphy.gif',
        'https://media.giphy.com/media/fMXMFkdqpLEKA/giphy.gif',
        'https://media.giphy.com/media/xT9IghFFcrwYHWZCgM/giphy.gif',
    ],
    'dragon-ball': [
        'https://media.giphy.com/media/4oB3Iwl9G49Ow/giphy.gif',
        'https://media.giphy.com/media/4oB3Iwl9G49Ow/giphy.gif',
        'https://media.giphy.com/media/fpufWhcJKJcXK/giphy.gif',
        'https://media.giphy.com/media/O7ycjTYBvzQek/giphy.gif',
        'https://media.giphy.com/media/O7ycjTYBvzQek/giphy.gif',
        'https://media.giphy.com/media/CfMo9X17WR6W4/giphy.gif',
        'https://media.giphy.com/media/7r0j1wNMWMR3i/giphy.gif',
        'https://media.giphy.com/media/7r0j1wNMWMR3i/giphy.gif',
        'https://media.giphy.com/media/fIQkFFMOKhi8M/giphy.gif',
        'https://media.giphy.com/media/RihThkWxzFENW/giphy.gif',
        'https://media.giphy.com/media/ha9VUXSEATSHS/giphy.gif',
        'https://media.giphy.com/media/zxy9vdsBSYEkE/giphy.gif',
        'https://media.giphy.com/media/12zsMO4Op2YlkQ/giphy.gif',
        'https://media.giphy.com/media/12zsMO4Op2YlkQ/giphy.gif',
        'https://media.giphy.com/media/eebmNnxxtSNiw/giphy.gif',
        'https://media.giphy.com/media/8xFaJbVmJpNhm/giphy.gif',
        'http://media.giphy.com/media/4vCXoOJIEpXYk/giphy.gif',
        'https://media.giphy.com/media/8cljB4ILmzjKE/giphy.gif',
        'https://media.giphy.com/media/R0yfvVNFqSmgU/giphy.gif',
        'https://media.giphy.com/media/13HtwCnSoc1ZdK/giphy.gif',
        'https://media.giphy.com/media/g7oEg8g2jukE0/giphy.gif',
        'https://media.giphy.com/media/tgWX6N4nHQjNC/giphy.gif',
        'https://media.giphy.com/media/ykbXCsOwfp1dK/giphy.gif',
        'https://media.giphy.com/media/8QtP5TqscKh3O/giphy.gif',
        'https://media.giphy.com/media/zDAqUralC0HU4/giphy.gif',
        'https://media.giphy.com/media/RhPlRgkE8mvE4/giphy.gif',
    ]

}




