
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-31T11:07:38+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b63f6addc0fc94916f32496bd1e2867ecf201ecf",
 "version": "1.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
