# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .compute_connector_properties_aws import ComputeConnectorPropertiesAws
from .compute_connector_properties_azure import ComputeConnectorPropertiesAzure
from .compute_connector_properties_gcp import ComputeConnectorPropertiesGcp


class ConnectorInputComputeProperties_Azure(ComputeConnectorPropertiesAzure):
    compute_type: typing_extensions.Literal["AZURE"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ConnectorInputComputeProperties_Aws(ComputeConnectorPropertiesAws):
    compute_type: typing_extensions.Literal["AWS"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ConnectorInputComputeProperties_Gcp(ComputeConnectorPropertiesGcp):
    compute_type: typing_extensions.Literal["GCP"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


ConnectorInputComputeProperties = typing.Union[
    ConnectorInputComputeProperties_Azure, ConnectorInputComputeProperties_Aws, ConnectorInputComputeProperties_Gcp
]
