# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .asset_classes_props import AssetClassesProps
from .classification_result_example import ClassificationResultExample


class DataClassItem(pydantic.BaseModel):
    name: str
    category: typing.Optional[str]
    id: str
    count: typing.Optional[int]
    matched_examples: typing.Optional[typing.List[ClassificationResultExample]]
    column_names: typing.Optional[typing.List[str]]
    properties: typing.Optional[AssetClassesProps]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
